Repository TencentBlueKing/bk-audit, pull requests merged in 2023-10, with the labels that each got.

#2 fix: invalid staging of itsm api
  src/backend/api/utils.py
Labels: bug

#3 fix: invalid staging of itsm api
  src/backend/api/utils.py
Labels: bug

#4 Dev
  src/backend/api/utils.py
Labels: bug

#8 perf: 前端代码格式化
  src/frontend/.husky/commit-msg
  src/frontend/.husky/pre-commit
  src/frontend/components.d.ts
  src/frontend/package.json
  src/frontend/src/components/auth/router-link.vue
  src/frontend/src/components/render-list/index.vue
  src/frontend/src/css/common.css
  src/frontend/src/css/reset.css
  src/frontend/src/directives/cursor/index.css
  src/frontend/src/main.ts
  src/frontend/src/utils/validate-monaco-editor.ts
  src/frontend/src/views/risk-manage/detail/components/risk-handle/components/button/mark-misreport.vue
  src/frontend/src/views/system-manage/collector-create/index.vue
  src/frontend/src/views/system-manage/detail/components/data-report/components/log-collection/index.vue
  src/frontend/stylelint.config.js
  src/frontend/tsconfig.config.json
  src/frontend/tsconfig.json
Labels: enhancement

#9 dev
  src/backend/apps/meta/models.py
  src/backend/apps/meta/resources.py
  src/backend/apps/meta/tasks.py
  src/backend/apps/permission/dispatcher.py
  src/backend/services/web/databus/collector/etl/etl_config_handler/bk_log_delimiter.py
  src/backend/services/web/databus/collector/etl/etl_config_handler/bk_log_json.py
  src/backend/services/web/databus/collector/etl/etl_config_handler/bk_log_regexp.py
  src/backend/services/web/databus/collector/handlers.py
  src/backend/services/web/databus/tasks.py
  src/backend/services/web/entry/handler/entry.py
  src/backend/services/web/entry/handler/healthz.py
  src/backend/services/web/version/resources.py
  src/backend/support-files/__init__.py
  src/backend/tests/meta/constants.py
  src/backend/tests/meta/test_meta.py
  src/backend/tests/risk/test_tickets/test_new.py
  src/backend/tests/version/test_version.py
  src/frontend/.husky/commit-msg
  src/frontend/.husky/pre-commit
  src/frontend/components.d.ts
  src/frontend/package.json
  src/frontend/src/components/auth/router-link.vue
  src/frontend/src/components/render-list/index.vue
  src/frontend/src/css/common.css
  src/frontend/src/css/reset.css
  src/frontend/src/directives/cursor/index.css
  src/frontend/src/main.ts
  src/frontend/src/utils/validate-monaco-editor.ts
  src/frontend/src/views/risk-manage/detail/components/risk-handle/components/button/mark-misreport.vue
  src/frontend/src/views/system-manage/collector-create/index.vue
  src/frontend/src/views/system-manage/detail/components/data-report/components/log-collection/index.vue
  src/frontend/stylelint.config.js
  src/frontend/tsconfig.config.json
  src/frontend/tsconfig.json
Labels: enhancement

#13 fix: 锁定依赖包版本
  src/frontend/package.json
Labels: bug

#14 fix: 依赖包版本升级
  src/frontend/package.json
Labels: bug

#16 Dev
  readme.md
  readme_en.md
  release.md
  src/backend/VERSION
  src/backend/app_desc.yaml
  src/backend/services/web/risk/handlers/risk.py
  src/backend/services/web/risk/handlers/ticket.py
  src/backend/services/web/risk/tasks.py
  src/backend/version_md/V1.6.1_20231024_en.md
  src/backend/version_md/V1.6.1_20231024_zh-cn.md
  src/frontend/package.json
Labels: feature

#17 feat: only use rule when operator is not none
  src/backend/services/web/risk/handlers/ticket.py
Labels: feature

#18 Dev
  src/backend/services/web/risk/handlers/ticket.py
Labels: feature
